<!DOCTYPE html>
    <head>
        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-TGRHWSL');</script>
        <!-- End Google Tag Manager -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" sizes="180x180" href="/img/rocket/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/img/rocket/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/img/rocket/favicon-16x16.png">
        <link rel="manifest" href="/img/rocket/site.webmanifest">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        <?php if(ENV == "prod" && $this->dispatcher->getControllerName() == 'Public') { ?>
            <meta name="robots" content="all">
        <?php } else { ?>
            <meta name="robots" content="noindex">
        <?php } ?>
        <?php if($this->dispatcher->getControllerName() == 'Public' && ($this->dispatcher->getActionName() == 'index' || $this->dispatcher->getActionName() == 'entrance')) { ?>
        <meta name="description" content="NFT Cryptokart is a collaborative non-fungible token art project launched on the Ethereum blockchain.">
        <meta content="NFT Cryptokart, First original collaborative NFT project" property="og:title"/>
        <meta content="/img/rocket/nftrocket.png" property="og:image"/>
        <meta content="NFT Cryptokart, First original collaborative NFT project" property="twitter:title"/>
        <meta content="NFT Cryptokart is a collaborative non-fungible token art project launched on the Ethereum blockchain." property="twitter:description"/>
        <meta content="/img/rocket/nftrocket.png" property="twitter:image"/>
        <meta property="og:type" content="website"/>
        <meta content="summary_large_image" name="twitter:card"/>
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <?php }?>
        <title><?php echo $this->view->title ?>NFT Cryptokart</title>
        <?php $this->assets->outputCss() ?>
    </head>
    <body class="smm-home dark-version">
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TGRHWSL"
                      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
        <?php echo $this->getContent(); ?>
        <?php $this->assets->outputJs(); ?>
        <?php
        $analyticsId = $this->config->envconf->analyticsId; ?>

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="/gascript/<?=$analyticsId; ?>"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', '<?=$analyticsId?>');
            //<?=ENV?>
            //<?=BASE_URL?>
        </script>
        <!-- 0xc473E73C7d0D2C387DeA4BC95fD4fc91c70e3562 -->
    </body>
</html>